/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.sample.gradle.kotest

import io.kotest.core.spec.style.WordSpec
import io.kotest.matchers.shouldBe


class MyTests : WordSpec({
    "Hello" When {
        "asked for length" should {
            "return 5" {
                "Hello".length shouldBe 5
            }
        }
        "appended to Bob" should {
            "return Hello Bob" {
                "Hello " + "Bob" shouldBe "Hello Bob"
            }
        }
    }
})
